# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- PROD

pool:
  vmImage: windows-latest

steps:
- task: gitsync@1
  inputs:
    GitRepoUrl: 'https://github.com/BassBoulder/AzureDeployment.git'